<?php

namespace Tests\Feature;

use App\Domain\Metadata\CoverDownloadService;
use App\Models\Library;
use App\Models\MediaBook;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * Manual cover upload/delete from the media item detail dialog (edit ->
 * upload a cover; the thumbnail alongside it is generated by
 * CoverDownloadService, see CoverDownloadServiceTest for that logic
 * itself). Also covers a cover's files getting cleaned up when the item
 * that owns them is deleted, which used to leave them orphaned on disk
 * forever — found while building this feature.
 */
class MediaItemCoverUploadTest extends TestCase
{
    use RefreshDatabase;

    private function actingAsUser(string $level = 'user'): User
    {
        $user = User::factory()->create(['level' => $level, 'is_active' => true]);
        $this->actingAs($user);

        return $user;
    }

    private function createBook(int $ownerId, array $attributes = []): MediaBook
    {
        $library = Library::query()->create(['name' => 'Novels', 'media_type' => 'book', 'owner_id' => $ownerId]);

        return MediaBook::query()->create([
            'library_id' => $library->id,
            'title' => 'Dune',
            'ean' => '9780000000001',
            ...$attributes,
        ]);
    }

    public function test_owner_can_upload_a_cover(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $item = $this->createBook($owner->id);

        $response = $this->post(
            "/api/libraries/{$item->library_id}/items/{$item->id}/cover",
            ['cover' => UploadedFile::fake()->image('cover.jpg', 400, 600)]
        );

        $response->assertOk();
        $this->assertNotNull($item->fresh()->cover_path);
        Storage::disk('local')->assertExists($item->fresh()->cover_path);
    }

    public function test_uploading_a_cover_generates_a_thumbnail_too(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $item = $this->createBook($owner->id);

        $this->post(
            "/api/libraries/{$item->library_id}/items/{$item->id}/cover",
            ['cover' => UploadedFile::fake()->image('cover.jpg', 400, 600)]
        )->assertOk();

        $thumbnailPath = app(CoverDownloadService::class)->thumbnailPath($item->fresh()->cover_path);
        Storage::disk('local')->assertExists($thumbnailPath);
    }

    public function test_uploading_a_new_cover_replaces_and_deletes_the_old_files(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $item = $this->createBook($owner->id);
        $coverService = app(CoverDownloadService::class);
        $oldPath = $coverService->uploadFromFile(UploadedFile::fake()->image('old.jpg'), 'book', $item->ean);
        $item->update(['cover_path' => $oldPath]);
        $oldThumbnailPath = $coverService->thumbnailPath($oldPath);

        $this->post(
            "/api/libraries/{$item->library_id}/items/{$item->id}/cover",
            ['cover' => UploadedFile::fake()->image('new.jpg', 400, 600)]
        )->assertOk();

        $this->assertNotSame($oldPath, $item->fresh()->cover_path);
        Storage::disk('local')->assertMissing($oldPath);
        Storage::disk('local')->assertMissing($oldThumbnailPath);
        Storage::disk('local')->assertExists($item->fresh()->cover_path);
    }

    public function test_upload_rejects_a_non_image_file(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $item = $this->createBook($owner->id);

        $response = $this->post(
            "/api/libraries/{$item->library_id}/items/{$item->id}/cover",
            ['cover' => UploadedFile::fake()->create('not-a-cover.pdf', 10)]
        );

        $response->assertStatus(422);
        $this->assertNull($item->fresh()->cover_path);
    }

    public function test_upload_requires_write_access(): void
    {
        Storage::fake('local');
        $owner = User::factory()->create(['level' => 'user', 'is_active' => true]);
        $item = $this->createBook($owner->id);
        $this->actingAsUser(); // a different, unrelated user

        $response = $this->post(
            "/api/libraries/{$item->library_id}/items/{$item->id}/cover",
            ['cover' => UploadedFile::fake()->image('cover.jpg')]
        );

        $response->assertForbidden();
        $this->assertNull($item->fresh()->cover_path);
    }

    public function test_owner_can_delete_a_cover(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $coverService = app(CoverDownloadService::class);
        $item = $this->createBook($owner->id);
        $path = $coverService->uploadFromFile(UploadedFile::fake()->image('cover.jpg'), 'book', $item->ean);
        $item->update(['cover_path' => $path]);
        $thumbnailPath = $coverService->thumbnailPath($path);

        $response = $this->delete("/api/libraries/{$item->library_id}/items/{$item->id}/cover");

        $response->assertOk();
        $this->assertNull($item->fresh()->cover_path);
        Storage::disk('local')->assertMissing($path);
        Storage::disk('local')->assertMissing($thumbnailPath);
    }

    public function test_delete_cover_requires_write_access(): void
    {
        Storage::fake('local');
        $owner = User::factory()->create(['level' => 'user', 'is_active' => true]);
        $item = $this->createBook($owner->id, ['cover_path' => 'covers/book/dune.jpg']);
        Storage::disk('local')->put('covers/book/dune.jpg', 'fake-bytes');
        $this->actingAsUser();

        $response = $this->delete("/api/libraries/{$item->library_id}/items/{$item->id}/cover");

        $response->assertForbidden();
        $this->assertNotNull($item->fresh()->cover_path);
        Storage::disk('local')->assertExists('covers/book/dune.jpg');
    }

    public function test_deleting_a_cover_that_does_not_exist_is_a_harmless_no_op(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $item = $this->createBook($owner->id);

        $response = $this->delete("/api/libraries/{$item->library_id}/items/{$item->id}/cover");

        $response->assertOk();
        $this->assertNull($item->fresh()->cover_path);
    }

    public function test_thumbnail_endpoint_serves_the_generated_thumbnail(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $coverService = app(CoverDownloadService::class);
        $item = $this->createBook($owner->id);
        $path = $coverService->uploadFromFile(UploadedFile::fake()->image('cover.jpg', 400, 600), 'book', $item->ean);
        $item->update(['cover_path' => $path]);

        $response = $this->get("/api/libraries/{$item->library_id}/items/{$item->id}/cover/thumbnail");

        $response->assertOk();
        $this->assertSame(
            Storage::disk('local')->get($coverService->thumbnailPath($path)),
            $response->streamedContent()
        );
    }

    public function test_thumbnail_endpoint_falls_back_to_the_full_cover_when_no_thumbnail_exists(): void
    {
        Storage::fake('local');
        // Simulates an item whose cover_path predates thumbnail generation — only the
        // original file exists on disk, no thumb_ file next to it.
        Storage::disk('local')->put('covers/book/dune.jpg', 'legacy-cover-bytes');
        $owner = $this->actingAsUser();
        $item = $this->createBook($owner->id, ['cover_path' => 'covers/book/dune.jpg']);

        $response = $this->get("/api/libraries/{$item->library_id}/items/{$item->id}/cover/thumbnail");

        $response->assertOk();
        $this->assertSame('legacy-cover-bytes', $response->streamedContent());
    }

    public function test_thumbnail_endpoint_404s_when_the_item_has_no_cover_at_all(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $item = $this->createBook($owner->id);

        $response = $this->get("/api/libraries/{$item->library_id}/items/{$item->id}/cover/thumbnail");

        $response->assertNotFound();
    }

    public function test_deleting_a_media_item_also_deletes_its_cover_and_thumbnail_files(): void
    {
        Storage::fake('local');
        $owner = $this->actingAsUser();
        $coverService = app(CoverDownloadService::class);
        $item = $this->createBook($owner->id);
        $path = $coverService->uploadFromFile(UploadedFile::fake()->image('cover.jpg'), 'book', $item->ean);
        $item->update(['cover_path' => $path]);
        $thumbnailPath = $coverService->thumbnailPath($path);
        Storage::disk('local')->assertExists($path);
        Storage::disk('local')->assertExists($thumbnailPath);

        $response = $this->delete("/api/libraries/{$item->library_id}/items/{$item->id}");

        $response->assertNoContent();
        Storage::disk('local')->assertMissing($path);
        Storage::disk('local')->assertMissing($thumbnailPath);
    }
}
