<?php

namespace App\Http\Controllers\Api;

use App\Domain\Libraries\CurrencyConversionService;
use App\Domain\Libraries\DuplicateEanException;
use App\Domain\Libraries\LibraryAccessService;
use App\Domain\Libraries\MediaItemService;
use App\Domain\Metadata\CoverDownloadService;
use App\Http\Controllers\Controller;
use App\Models\Library;
use App\Models\SystemSetting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

/**
 * Media item CRUD, scoped to a single library and its fixed media_type
 * (briefing 6.). One controller for all three types rather than three
 * near-identical ones — the type-specific model/attributes are resolved via
 * MediaItemService::modelClassFor($library->media_type).
 */
class MediaItemController extends Controller
{
    public function __construct(
        private readonly LibraryAccessService $access,
        private readonly MediaItemService $mediaItemService,
        private readonly CoverDownloadService $coverDownloadService,
        private readonly CurrencyConversionService $currencyConversion,
    ) {}

    public function index(Request $request, Library $library)
    {
        abort_unless($this->access->canRead($request->user(), $library), 403);

        $query = $library->mediaItems();

        $sortBy = $request->string('sort_by')->toString();
        if (in_array($sortBy, MediaItemService::SORTABLE_COLUMNS[$library->media_type], true)) {
            $direction = $request->string('sort_dir')->toString() === 'desc' ? 'desc' : 'asc';
            $query->orderBy($sortBy, $direction);
        }

        // GitHub issue #194: an explicit `per_page` query param still wins
        // (unchanged behavior for any existing caller), but the default
        // when none is given is now the requesting user's own stored
        // preference (User::ITEMS_PER_PAGE_OPTIONS) rather than a flat 50 —
        // this is the *only* place that preference needs to be read, since
        // LibraryDetailPage.tsx never sends per_page itself.
        return $query->paginate($request->integer('per_page', $request->user()?->items_per_page ?? 50));
    }

    public function show(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canRead($request->user(), $library), 403);

        return $library->mediaItems()->findOrFail($item);
    }

    /**
     * Streams a stored cover image (see CoverDownloadService, briefing 8.3
     * step 5). Served through the API rather than a direct storage URL —
     * covers live on the `local` disk, not `public` (see
     * CoverDownloadService's docblock) — which also means this gets the
     * same LibraryAccessService::canRead() check every other read of this
     * library's items already goes through (4.3: unshared -> invisible).
     */
    public function cover(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canRead($request->user(), $library), 403);

        $record = $library->mediaItems()->findOrFail($item);

        return $this->streamCover($record->cover_path);
    }

    /**
     * The library item-list view's small cover (LibraryDetailPage.tsx) —
     * generated by CoverDownloadService alongside the full cover so the
     * list doesn't ship a full-size image to every row. Falls back to the
     * full cover for an item whose cover_path predates this feature (no
     * thumbnail was ever generated for it) rather than 404ing — same
     * "best effort" stance CoverDownloadService itself takes toward
     * thumbnail generation failing.
     */
    public function coverThumbnail(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canRead($request->user(), $library), 403);

        $record = $library->mediaItems()->findOrFail($item);

        if (! $record->cover_path) {
            abort(404);
        }

        $thumbnailPath = $this->coverDownloadService->thumbnailPath($record->cover_path);
        $path = Storage::disk('local')->exists($thumbnailPath) ? $thumbnailPath : $record->cover_path;

        return $this->streamCover($path);
    }

    private function streamCover(?string $path)
    {
        abort_if(! $path, 404);
        // Defense in depth — see CoverDownloadService::isManagedPath()'s docblock.
        abort_unless($this->coverDownloadService->isManagedPath($path), 404);

        return Storage::disk('local')->response($path);
    }

    /**
     * Uploads/replaces the item's cover (media item detail dialog's "upload
     * cover" action). The old cover+thumbnail (if any) are only deleted
     * once the new one is safely stored — so a failed upload never leaves
     * the item without the cover it had before.
     */
    public function uploadCover(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $record = $library->mediaItems()->findOrFail($item);
        $data = $request->validate([
            // 5120 KB matches CoverDownloadService::MAX_BYTES (5 MB) — kept in sync
            // manually since Laravel's `max:` rule wants kilobytes, not bytes.
            'cover' => ['required', 'image', 'max:5120'],
        ]);

        $newPath = $this->coverDownloadService->uploadFromFile($data['cover'], $library->media_type, $record->ean);

        abort_if($newPath === null, 422, 'Uploaded file could not be processed as an image.');

        $oldPath = $record->cover_path;
        $record->update(['cover_path' => $newPath]);
        $this->coverDownloadService->delete($oldPath);

        return $record;
    }

    /** Removes the item's cover — clears cover_path and deletes both the original and thumbnail files (media item detail dialog's "remove cover" action). */
    public function deleteCover(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $record = $library->mediaItems()->findOrFail($item);
        $this->coverDownloadService->delete($record->cover_path);
        $record->update(['cover_path' => null]);

        return $record;
    }

    /**
     * Single-entry capture (briefing 7.1). Duplicate EANs within the
     * library are strictly rejected (5.1) — no auto stock increase.
     */
    public function store(Request $request, Library $library)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $data = $request->validate([
            ...$this->rulesFor($library->media_type),
            // GitHub issue #166: a candidate chosen from CapturePage.tsx's
            // free-text "ohne EAN erfassen" search (issue #151) carries a
            // cover image URL of its own — MetadataController::import()
            // (the EAN/merge-review confirm path) already downloads a
            // cover this same way; this form previously had no equivalent
            // at all, so a candidate's cover — visibly shown in the search
            // results list — silently never made it onto the created item.
            // Not part of rulesFor() itself since it's request-only
            // metadata about *where to get* the cover, not a stored
            // MediaBook/MediaCd/MediaDvdBluray column the way every other
            // rulesFor() field is.
            'cover_url' => ['nullable', 'string'],
        ]);
        $coverUrl = $data['cover_url'] ?? null;
        unset($data['cover_url']);

        // GitHub issue #64: a live-converted price stays meaningful in
        // StatisticsService::overviewFor()'s sum('price') without that
        // service needing to know about multiple currencies at all — see
        // CurrencyConversionService's docblock. A no-op when no default
        // currency is configured, no price/currency was entered, or it
        // already matches the default.
        $data = $this->currencyConversion->convertToDefaultCurrency($data);

        // GitHub issue #74: this endpoint is only ever reached from the
        // standalone "Add manually" form (CreateMediaItemDialog.tsx) —
        // MetadataController::import() is the one confirmed candidates
        // route through, see that method's own capture_method='scan'. Not
        // validated/client-supplied like the rest of $data, and not in
        // rulesFor() either — an internally computed fact about *how* this
        // request arrived, not item data a caller gets to assert.
        $data['capture_method'] = 'manual';
        $data['metadata_provider'] = null;
        $data['captured_by_user_id'] = $request->user()->id;

        // GitHub issue #151: EAN is now optional on this form (rulesFor()
        // below) — a media item genuinely without one still needs a value
        // for the NOT NULL, per-library-unique `ean` column, so an empty
        // submission gets a generated placeholder instead.
        if (empty($data['ean'])) {
            $data['ean'] = $this->mediaItemService->generateNoEanPlaceholder($library);
        }

        try {
            $item = $this->mediaItemService->create($library, $data);
        } catch (DuplicateEanException $e) {
            return response()->json(['message' => $e->getMessage(), 'ean' => $e->ean], 409);
        }

        // GitHub issue #166 — same "download server-side, then attach"
        // shape MetadataController::import()/reimport() already use. A
        // failed download (dead link, blocked host, ...) leaves the item
        // exactly as created, without a cover, rather than failing the
        // whole capture over an optional enrichment.
        if (! empty($coverUrl)) {
            $coverPath = $this->coverDownloadService->download($coverUrl, $library->media_type, $item->ean);

            if ($coverPath) {
                $item->update(['cover_path' => $coverPath]);
            }
        }

        return response()->json($item, 201);
    }

    public function update(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $record = $library->mediaItems()->findOrFail($item);
        $rules = $this->rulesFor($library->media_type);
        // GitHub issue #201: editing the EAN is admin-only, deliberately
        // narrower than canWriteItems() above (which also lets a plain
        // owner or write-share user through) — "für normale Benutzer soll
        // diese Möglichkeit bewusst nicht bestehen" was explicit. A
        // non-admin gets exactly the same behavior as before this issue:
        // 'ean' isn't a recognized field at all, so it's silently dropped
        // like any other unvalidated key rather than erroring. GitHub issue
        // #202 adds a second, admin-configurable gate on top: an admin whose
        // instance has disabled the editor entirely (AdminSettingsController::
        // updateEanEditing()) gets the exact same "silently dropped" fallback
        // — checked server-side on every request rather than trusting that
        // the frontend has hidden the editor, since a stale page or a direct
        // API call could still send the field otherwise.
        $isAdmin = $request->user()->isAdmin() && SystemSetting::get('ean_editing.enabled', false);
        if (! $isAdmin) {
            unset($rules['ean']);
        }
        // Drop 'required' specifically (title is the only field that has it —
        // everything else in rulesFor() already starts with 'nullable') rather
        // than positionally slicing off index 0. array_slice($rule, 1) used to
        // sit here and silently discarded whichever rule happened to come
        // first — for every 'nullable' field (i.e. everything except title)
        // that meant discarding 'nullable' itself, so PUTting an explicit
        // `null` to clear an optional field (e.g. from the media item detail
        // dialog's edit form) 422ed with "must be a string" instead of
        // clearing it. Confirmed live against a running dev server while
        // building that dialog — no prior UI ever sent an explicit null for
        // these fields, so this had gone unnoticed.
        $data = $request->validate(array_map(
            fn ($rule) => ['sometimes', ...array_values(array_diff($rule, ['required']))],
            $rules
        ));

        // GitHub issue #201: the edit dialog's three EAN options —
        // "bisherige EAN behalten" (the 'ean' key simply isn't sent at all,
        // so it never reaches $data), "neue EAN eingeben" (a non-empty
        // string), or "automatisch generieren" (an empty/omitted-after-
        // validation value, the exact same "blank means generate a NoEAN-...
        // placeholder" convention store() already uses) — collapse to a
        // single "the value this item's EAN should end up with" here,
        // checked against the library's own duplicate rule *before* it (or
        // any other field in this same request) is written to the
        // database, per the issue's own explicit requirement.
        if ($isAdmin && array_key_exists('ean', $data)) {
            $newEan = $data['ean'] !== null && $data['ean'] !== ''
                ? $data['ean']
                : $this->mediaItemService->generateNoEanPlaceholder($library);

            try {
                $this->mediaItemService->assertEanAvailable($library, $newEan, $record->id);
            } catch (DuplicateEanException $e) {
                return response()->json(['message' => $e->getMessage(), 'ean' => $e->ean], 409);
            }

            $data['ean'] = $newEan;
        } else {
            unset($data['ean']);
        }

        // GitHub issue #90: a manual edit of a CD's `tracks` (rulesFor('cd')
        // already accepts it) needs the same runtime_seconds/runtime_computed
        // re-derivation the capture/reimport paths get via
        // MediaItemService::create()/updateFromMetadata() — otherwise a
        // hand-corrected track list would leave a stale runtime in place.
        // A no-op for every other field/media type (see withDerivedRuntime()'s
        // own docblock).
        $record->update($this->mediaItemService->withDiscCountDefault($this->mediaItemService->withDerivedRuntime($data)));

        return $record;
    }

    public function destroy(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $record = $library->mediaItems()->findOrFail($item);
        $coverPath = $record->cover_path;
        $record->delete();
        // Otherwise an item's cover+thumbnail files sat on disk forever, orphaned —
        // nothing ever referenced them again once the record itself was gone.
        $this->coverDownloadService->delete($coverPath);

        return response()->noContent();
    }

    /**
     * Bulk-delete (GitHub issue #54, briefing 7.) — the multi-select
     * counterpart to destroy() above, same write-access check and the same
     * per-item cover/thumbnail cleanup, just looped over every requested id
     * instead of one.
     *
     * `whereIn('id', ...)` scoped through `$library->mediaItems()` (not a
     * bare `MediaBook::whereIn(...)`) is what keeps this from letting a
     * request delete an item belonging to a *different* library just
     * because its id happened to be included — same containment
     * destroy()'s single-item findOrFail() already gets from the same
     * relation. Unlike destroy(), an id that doesn't exist in this library
     * (already deleted by someone else, a stale selection, a typo'd id) is
     * silently skipped rather than 404ing the whole request — a bulk
     * operation over a list is inherently "best effort per item", not one
     * strict single-record lookup.
     */
    public function bulkDestroy(Request $request, Library $library)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $data = $request->validate([
            'ids' => ['required', 'array', 'min:1'],
            'ids.*' => ['integer'],
        ]);

        $records = $library->mediaItems()->whereIn('id', $data['ids'])->get();

        foreach ($records as $record) {
            $coverPath = $record->cover_path;
            $record->delete();
            $this->coverDownloadService->delete($coverPath);
        }

        return response()->json(['deleted_ids' => $records->pluck('id')->values()]);
    }

    /**
     * Bulk-update (GitHub issue #63, the general follow-up #54's own
     * proposal text named as a possible next step) — sets exactly one
     * field to one shared value across every selected item, e.g. changing
     * "Genre" for a dozen selected books at once. Same write-access check
     * and same cross-library containment via `$library->mediaItems()` as
     * bulkDestroy() above.
     *
     * `field` is validated against rulesFor() — the same medium-type-
     * dependent field list update() already uses for a single item — minus
     * `ean` (unchangeable here for the same reason update() already
     * excludes it) and minus `tracks`/`runtime_seconds`/`runtime_computed`
     * (CD, GitHub issue #48): `tracks` isn't a single scalar value a bulk
     * "set this field to this value" operation can represent, and
     * `runtime_seconds` is only ever *derived* from whichever `tracks` a
     * record actually has (MediaItemService::withDerivedRuntime()) rather
     * than chosen independently — setting it here directly would risk it
     * silently disagreeing with the record's own `tracks`.
     *
     * `value` is validated against that one field's *own* rule, unmodified
     * — unlike update()'s "make everything optional, drop 'required'"
     * rewrite (which exists because a PUT payload is partial and an absent
     * key means "leave untouched"), a bulk-update request always supplies
     * `value` for the one field it names, so `title`'s `required` rule is
     * deliberately kept intact: bulk-clearing every selected item's title
     * to empty would violate the same invariant a single edit already
     * enforces.
     */
    public function bulkUpdate(Request $request, Library $library)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $rules = $this->rulesFor($library->media_type);
        unset($rules['ean'], $rules['tracks'], $rules['runtime_seconds'], $rules['runtime_computed']);

        $selection = $request->validate([
            'ids' => ['required', 'array', 'min:1'],
            'ids.*' => ['integer'],
            'field' => ['required', 'string', Rule::in(array_keys($rules))],
        ]);

        $value = $request->validate(['value' => $rules[$selection['field']]])['value'];

        $records = $library->mediaItems()->whereIn('id', $selection['ids'])->get();

        // GitHub issue #155: bulk-clearing disc_count the same way a
        // single edit's blank field would hits the exact same NOT NULL
        // column default gap — see withDiscCountDefault()'s own docblock.
        $update = $this->mediaItemService->withDiscCountDefault([$selection['field'] => $value]);

        foreach ($records as $record) {
            $record->update($update);
        }

        return response()->json(['updated_ids' => $records->pluck('id')->values()]);
    }

    /**
     * Moves a media item into a different library (media item detail
     * dialog's "move" action). Requires write access to *both* libraries —
     * moving something out of a library the user doesn't own/administer
     * would let them empty it out from under its actual owner, and moving
     * into one they can't write to would bypass that library's own write
     * protection entirely. Restricted to same-media_type libraries: the
     * record's model class only fits one specific media_type's table (see
     * MediaItemService::move()'s docblock), so this isn't just a policy
     * choice.
     */
    public function move(Request $request, Library $library, int $item)
    {
        abort_unless($this->access->canWriteItems($request->user(), $library), 403);

        $record = $library->mediaItems()->findOrFail($item);
        $data = $request->validate([
            'target_library_id' => ['required', 'integer', 'exists:'.(new Library)->getTable().',id'],
        ]);

        $target = Library::query()->findOrFail($data['target_library_id']);
        abort_unless($this->access->canWriteItems($request->user(), $target), 403);

        if ($target->id === $library->id) {
            return response()->json(['error_code' => 'same_library', 'message' => 'Item is already in this library.'], 422);
        }

        if ($target->media_type !== $library->media_type) {
            return response()->json(['error_code' => 'media_type_mismatch', 'message' => 'Target library has a different media type.'], 422);
        }

        try {
            $this->mediaItemService->move($record, $target);
        } catch (DuplicateEanException $e) {
            return response()->json(['message' => $e->getMessage(), 'ean' => $e->ean], 409);
        }

        return $record->fresh();
    }

    private function rulesFor(string $mediaType): array
    {
        return match ($mediaType) {
            'book' => [
                'title' => ['required', 'string', 'max:255'],
                // GitHub issue #151: optional — an empty submission gets a
                // generated NoEAN-{...} placeholder, see store()'s own comment.
                'ean' => ['nullable', 'string', 'max:13'],
                'description' => ['nullable', 'string'],
                'authors' => ['nullable', 'string'],
                'format' => ['nullable', 'string'],
                'genre' => ['nullable', 'string'],
                'page_count' => ['nullable', 'integer'],
                'language' => ['nullable', 'string', 'max:10'],
                'publisher' => ['nullable', 'string'],
                'release_date' => ['nullable', 'date'],
                'price' => ['nullable', 'numeric'],
                // GitHub issue #58: an ISO 4217 code (e.g. "USD"/"EUR"), not
                // validated against an actual currency list — this only
                // records what the admin/provider says it is.
                'currency' => ['nullable', 'string', 'max:3'],
                'isbn10' => ['nullable', 'string', 'max:10'],
                'isbn13' => ['nullable', 'string', 'max:13'],
                // GitHub issue #96: free text, not validated against a fixed
                // list — same "records whatever the user says" stance
                // `currency` above already takes.
                'location' => ['nullable', 'string'],
            ],
            'cd' => [
                'title' => ['required', 'string', 'max:255'],
                // GitHub issue #151: optional — an empty submission gets a
                // generated NoEAN-{...} placeholder, see store()'s own comment.
                'ean' => ['nullable', 'string', 'max:13'],
                'description' => ['nullable', 'string'],
                'artist' => ['nullable', 'string'],
                'medium' => ['nullable', 'string'],
                'asin' => ['nullable', 'string'],
                'disc_count' => ['nullable', 'integer', 'min:1'],
                // No nested 'tracks.*.title' etc. rules — a bare 'array' rule
                // already passes the whole submitted array through unchanged
                // (see MetadataController::import()'s docblock for why adding
                // nested rules under the same top-level key is a trap
                // elsewhere in this file — not applicable here since there's
                // no sibling data under 'tracks' itself to accidentally drop,
                // but simplest to just not need to reason about it at all).
                'tracks' => ['nullable', 'array'],
                'runtime_seconds' => ['nullable', 'integer', 'min:0'],
                'runtime_computed' => ['nullable', 'boolean'],
                'release_date' => ['nullable', 'date'],
                'price' => ['nullable', 'numeric'],
                // GitHub issue #58: an ISO 4217 code (e.g. "USD"/"EUR"), not
                // validated against an actual currency list — this only
                // records what the admin/provider says it is.
                'currency' => ['nullable', 'string', 'max:3'],
                // GitHub issue #96.
                'location' => ['nullable', 'string'],
            ],
            'dvd_bluray' => [
                'title' => ['required', 'string', 'max:255'],
                // GitHub issue #151: optional — an empty submission gets a
                // generated NoEAN-{...} placeholder, see store()'s own comment.
                'ean' => ['nullable', 'string', 'max:13'],
                'description' => ['nullable', 'string'],
                'medium' => ['nullable', 'string'],
                'disc_count' => ['nullable', 'integer', 'min:1'],
                'runtime_minutes' => ['nullable', 'integer'],
                'languages' => ['nullable', 'string'],
                // GitHub issue #140.
                'subtitles' => ['nullable', 'string'],
                'cast' => ['nullable', 'string'],
                'director' => ['nullable', 'string'],
                // GitHub issue #140 — same free-text shape as MediaBook::genre.
                'genre' => ['nullable', 'string'],
                'release_date' => ['nullable', 'date'],
                'production_year' => ['nullable', 'integer'],
                'price' => ['nullable', 'numeric'],
                // GitHub issue #58: an ISO 4217 code (e.g. "USD"/"EUR"), not
                // validated against an actual currency list — this only
                // records what the admin/provider says it is.
                'currency' => ['nullable', 'string', 'max:3'],
                // GitHub issue #96.
                'location' => ['nullable', 'string'],
            ],
        };
    }
}
